# Custom Language File for Launcher Customizer

[ejs.app]
title = "4kraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.youtube.com/@4KraftPVP"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@4KraftPVP"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/cedr0u/worksapcelauncher"
supportLink = "https://github.com/cedr0u/worksapcelauncher"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR 4kraft"
welcomeDescription = "4kraft un serveur survie modé avec plusieurs fonctionnalités et plusieurs modes de jeux par le futur."
welcomeDescCTA = "Plus que quelque clique pour rejoindre 4kraft."
